[user]
name = "Tolu A."
email = "tolu@adesegha.ca"

[ui]
editor = "nvim"

[aliases]
# Shorter log with a compact template
l = ["log", "--limit", "10"]
la = ["log", "-r", "all()"]

# Status shorthand
s = ["status"]

# Describe current change
m = ["describe", "-m"]

# New change (like git checkout -b)
n = ["new"]

# Edit change (like git checkout -b)
e = ["edit"]

# Squash into parent
sq = ["squash"]

# Push current branch
ps = ["git", "push"]

# Fetch from remote
pl = ["git", "fetch"]

d = ["diff"]

# Bookmark shorthand
bc = ["bookmark", "create"]
bt = ["bookmark", "track"]
bs = ["bookmark", "set", "--allow-backwards"]
