# remap prefix from 'C-b' to 'C-space'
unbind C-b
set-option -g prefix C-space
bind-key C-space send-prefix

# unbind commonly mistyped bindings
# unbind-key C-z

# split panes using | and -
unbind '"'
unbind %
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# switch to current path when creating a new window
bind c new-window -c "#{pane_current_path}"

# vim keys in copy mode
set -g mode-keys vi
bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
bind-key -T copy-mode-vi v send-keys -X begin-selection
# bind-key -T prefix p paste-buffer -p

# count from 1
set -g base-index 1
setw -g pane-base-index 1

set -g status-left-length 100 # allow more space for session names in the status bar

# stop delay after escape key
set -sg escape-time 0

# Smart pane switching with awareness of Vim splits.
# See: https://github.com/christoomey/vim-tmux-navigator
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?|fzf)(diff)?$'"
bind-key -n 'C-h' if-shell "$is_vim" 'send-keys C-h'  'select-pane -L'
bind-key -n 'C-t' if-shell "$is_vim" 'send-keys C-t'  'select-pane -D'
bind-key -n 'C-n' if-shell "$is_vim" 'send-keys C-n'  'select-pane -U'
bind-key -n 'C-s' if-shell "$is_vim" 'send-keys C-s'  'select-pane -R'

tmux_version='$(tmux -V | sed -En "s/^tmux ([0-9]+(.[0-9]+)?).*/\1/p")'
if-shell -b '[ "$(echo "$tmux_version < 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\'  'select-pane -l'"
if-shell -b '[ "$(echo "$tmux_version >= 3.0" | bc)" = 1 ]' \
    "bind-key -n 'C-\\' if-shell \"$is_vim\" 'send-keys C-\\\\'  'select-pane -l'"

bind-key -T copy-mode-vi 'C-h' select-pane -L
bind-key -T copy-mode-vi 'C-t' select-pane -D
bind-key -T copy-mode-vi 'C-n' select-pane -U
bind-key -T copy-mode-vi 'C-s' select-pane -R
bind-key -T copy-mode-vi 'C-\' select-pane -l

# quicker copy / scroll mode
bind -T prefix C-d copy-mode
bind -T prefix C-b copy-mode \; send-keys -X page-up
bind -T prefix C-u copy-mode \; send-keys -X halfpage-up
bind -T prefix C-_ copy-mode \; send-keys '?'

bind-key u capture-pane -J \; save-buffer /tmp/tmux-buffer \; delete-buffer \; split-window -l 10 "grep -oE '(https?|ftp)://[^[:space:]>\"]+' /tmp/tmux-buffer | sort -u | fzf | xargs open; tmux kill-pane"
