require("utils")
require("apps")
require("windows")
require("bluetooth")
require("config")
require("keypad")
require("projects")
require("switcher")
local tabstore = require("browser-tab-store")

hs.notify.new({title="Hammerspoon", informativeText="Config loaded"}):send()
tabstore.start()
