require("utils")
require("apps")
require("windows")
require("bluetooth")
require("config")
require("keypad")
require("projects")
require("paperwm_config")

hs.notify.new({title="Hammerspoon", informativeText="Config loaded"}):send()
